steps:
  # This step runs the unit tests on the app
  - name: "python:3.7-slim"
    id: Test
    entrypoint: /bin/sh
    args:
      - -c
      - "pip install flask"
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/${PROJECT_ID}/demo-cloudbuild:$SHORT_SHA", "."]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/demo-cloudbuild:$SHORT_SHA"]
